name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v5

      - name: Verify dependencies
        run: go mod tidy

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      
      - name: Run golint
        run: golint ./main.go

      - name: Build
        run: go build
